#page title
page_title                                : My Food Mart                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                        # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : My Food Mart                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your grocery app.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : my food mart
your_link                                 : https://www.myfoodmart.com.au
your_city                                 : Melbourne
email_address                             : admin@myfoodmart.com.au
facebook_username                         :
instagram_username                        : my.food.mart
twitter_username                          :
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Bundles
    description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
    icon                                  : assets/icons/bundles.png

  - title                                 : Hot / Specials
    description                           : Preview your app in the context of an iPhone device. Five different device colors included.
    icon                                  : assets/icons/hot.png

  - title                                 : Drinks
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    icon                                  : assets/icons/drinks.png

  - title                                 : Frozen
    description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
    icon                                  : assets/icons/freezer.png

  - title                                 : Fridge / Deli / Eggs
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    icon                                  : assets/icons/fridge.png

  - title                                 : Fruit and Vege
    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    icon                                  : assets/icons/fruitAndVeg.png

  - title                                 : Health and Beauty
    description                           : Display a smart app banner on iOS devices.
    icon                                  : assets/icons/health.png

  - title                                 : Hotpot
    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    icon                                  : assets/icons/hotpot.png

  - title                                 : Household Products
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    icon                                  : assets/icons/household.png

  - title                                 : Instant Foods
    description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
    icon                                  : assets/icons/instant.png

  - title                                 : Japanese
    description                           : Preview your app in the context of an iPhone device. Five different device colors included.
    icon                                  : assets/icons/japanese.png

  - title                                 : Korean
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    icon                                  : assets/icons/korean.png

  - title                                 : Liquor
    description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
    icon                                  : assets/icons/liquor.png

  - title                                 : Meat
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    icon                                  : assets/icons/meat.png

  - title                                 : Kitchen Pantry
    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    icon                                  : assets/icons/pantry.png

  - title                                 : Rice / Flour / Grains
    description                           : Display a smart app banner on iOS devices.
    icon                                  : assets/icons/rice.png

  - title                                 : Seafood
    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    icon                                  : assets/icons/seafood.png

  - title                                 : Snacks
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    icon                                  : assets/icons/snacks.png



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
